### ISSUE TITLE
Change index.html to welcome.html

### ISSUE THREAD

**Issue by Farris1** [Farris1/Farris1.github.io#1]
Hi everybody,

I want to change my index.html to welcome.html without it doing any harm to my file. So when I open up the website [find the website here](https://farris1.github.io/index.html) in the URL it will show up as farris1.github.io/welcome.html instead of farris1.github.io/index.html. 

Is this possible to fix? 
I really appreciate your help.
Thank you
![URL](https://user-images.githubusercontent.com/60323823/79488454-97809b80-7fce-11ea-881c-63457c6e3c86.JPG)

**Comment by eesypeesy** [comment]
@Farris1 
in your index.html, add this to the **header**

`<meta http-equiv="refresh" content="0; url=http://farris1.github.io/welcome.html" />`

Here, index.html actually acts as a dummy, and redirects to your contents in welcome.html.
(Careful with syntax)
Hope this helps!

**Comment by Farris1** [comment]
> @eesypeesy 
> Thank you for your help I really appreciate it. Is it that I also need a welcome.html file in my project so that it can redirect the content in welcome.html? I'm asking this because it shows a 404 error page. Thank you

**Comment by eesypeesy** [comment]
@Farris1 yes!

**Comment by Farris1** [comment]
> @eesypeesy 
I take that I need to copy and paste my index.html file content into my welcome.html. 
I'm I right?

Thank you in advance

**Comment by eesypeesy** [comment]
You copy the contents of index.html to welcome.html. Then you can empty out the contents in index.html if you want. Just keep the code i gave you inside  <head>

**Comment by Farris1** [comment]
> @eesypeesy 
Thank you very much for your amazing help. Your code really helped. Thanks for your help once again.

**Comment by Farris1** [comment]
> @eesypeesy 
Thank you this has worked. But my website keeps refreshing?

**Comment by eesypeesy** [comment]
Dont put that code in your welcome.html header :D

**Comment by Farris1** [comment]
> Thanks ill try it out :)

**Comment by Farris1** [comment]
> @eesypeesy 
Thanks for your help i really do appreciate it :) This code has worked so thank you very much
